apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-arcadia
spec:
  host: app.arcadia.com
  policies:
  - name: waf-policy
  upstreams:
  - name: main
    service: main
    port: 80
  - name: backend
    service: backend
    port: 80
  routes:
  - path: /
    action:
      pass: main
  - path: /files
    action:
      pass: backend
